// src/MaterialComponent.tsx
import { useEffect, useState } from 'react';
import { useParams } from "react-router-dom";

export type Material = {
	createdTime: string,
	id: string,
	fields: {
		Deploy: boolean,
		Name: string,
		Text: string,
		Attachments?: any[],
		ID: number
	}
}

export function MaterialComponent(props: { mode: 'old' | 'new' }) {

	const { id } = useParams()
	console.log(id, 'id');

	const [material, setMaterial] = useState<Material | null>(null);

	useEffect(() => {
		fetch(`https://api.airtable.com/v0/appOUfEIThjJfxZ4q/${props.mode}/${id}?api_key=keyYi2iEDJGoFI90C`)
			.then(async (r) => {
				let res = await r.json()
				console.log(res, 'res');
				if (res.fields.Attachments && res.fields.Attachments.length > 1) {
					res.fields.Attachments.shift()
				}
				setMaterial(res)
				document.title = res.fields.Name
			})
			.catch((e) => console.warn(e))
	}, [])

	return (
		<>
			<div className="container">
				<div style={{ width: '100%', display: 'flex', justifyContent: 'center', textAlign: 'center' }}>
					{material && <div>
						<h2>{material.fields.Name}</h2>
						{material.fields.Attachments && <div style={{display:'flex', gap: '20px', justifyContent: 'center', flexWrap: 'wrap' }}>
							{material.fields.Attachments?.map((e) => (
								<img src={e.thumbnails.large.url} alt="" style={{ width: '200px', height: '200px' }} />
							))}
						</div>}
						<div style={{ padding: '0 15px' }}>
							{material.fields.Text.split('|').map((a) => {
								return (
									<p>{a}</p>
								)
							})}
						</div>
					</div>}
					{!material && <span style={{ fontSize: '25px' }}>ЗАГРУЗКА...</span>}
				</div>
			</div>
		</>
	);
}

// src/routes/material/Material.svelte
<script lang="ts">
	// export let materialRoute: string;
	export let mode: "new" | "old";

	type Material = {
		createdTime: string;
		id: string;
		fields: {
			Deploy: boolean;
			Name: string;
			Text: string;
			Attachments?: string[];
			ID: number;
		};
	};

	let fetchMaterial = async () => {
		let res = await fetch(
			`https://api.airtable.com/v0/appOUfEIThjJfxZ4q/${mode}?api_key=keyYi2iEDJGoFI90C`
		);
		let result = (await res.json()) as Material;
		console.log(result, "result");
		return result;
	};
</script>

<svelte:head>
	<title>Material</title>
</svelte:head>

<div>
	{#await fetchMaterial()}
		<div style="text-align: center; padding: 20px 0;">
			<span style="font-size: 25px;">ЗАГРУЗКА...</span>
		</div>
	{:then result}
		<div class="container">
			<h1 style="text-align:center;">
				{result.fields.Name}
			</h1>
			<div style="display:flex; gap: 20px;">
				{#if result.fields.Attachments && result.fields.Attachments.length > 0}
					{#each result.fields.Attachments as img}
						<img src={img} alt="" />
					{/each}
				{/if}
			</div>
			<div
				style="width:100%; display:flex; justify-content: center; text-align: center;"
			>
				<div style="padding: 0 15px;">
					{#each result.fields.Text.split("|") as t}
						<p>{t}</p>
					{/each}
				</div>
			</div>
		</div>
	{/await}
</div>
